### ISSUE TITLE
may you clarify how to find ratings_Video_Games.csv 

### ISSUE THREAD

**Issue by Sandy4321** [karapostK/ProtoMF#1]
per what is written how to get data , may you clarify how to find ratings_Video_Games.csv on 
http://jmcauley.ucsd.edu/data/amazon/index_2014.html
or may be to use 
https://nijianmo.github.io/amazon/index.html

**Comment by karapostK** [comment]
Hey!
In the first page you sent -> Files -> Videogames -> "ratings only". Click on the link and you should download the right file.
